// app/intake-assistant/page.tsx
//
// The AI intake assistant demo, as a landing page for the searches Search
// Console shows landing here ("ai intake assistant" at ~23, "ai intake
// specialist for law firms", "intake assistant tool", "legal intake
// specialist ai").
//
// Every capability on this page is what the demo actually does — see the
// system prompt in app/api/intake-assistant/route.ts: it gathers incident,
// date, injuries, treatment, fault, insurance, police report, other counsel
// and location; it gives no legal advice, deadlines or case values; and it
// hands back a structured summary with an internal screening signal. It is a
// chat assistant: it does not answer phone calls, and there is no CRM
// integration, so the page claims neither.

import type { Metadata } from "next";
import Link from "next/link";
import { ClipboardList, MessageSquareText, ShieldCheck, Filter } from "lucide-react";
import IntakeAssistant from "@/app/components/intake-assistant/intake-assistant";
import ArticleLeadMagnet from "@/components/ArticleLeadMagnet";
import GuideMagnet from "@/components/GuideMagnet";
import { CardGrid, FaqList, FeatureCard, PageHero, Section, SectionHeading, Accent } from "@/components/layout";
import { LAW_CHECKLIST_GUIDE } from "@/lib/guides";
import { getPageSEO } from "@/lib/admin-seo";
import { SITE, founderRef, organizationRef, websiteRef } from "@/lib/site-schema";

const PAGE_URL = `${SITE}/intake-assistant`;
// Generated by ./opengraph-image.tsx; Next wires it into og:image itself, so
// this constant is only for the JSON-LD.
const OG_IMAGE = `${SITE}/intake-assistant/opengraph-image`;
const TITLE = "AI Intake Assistant for Law Firms: Live Demo";
const DESCRIPTION =
  "An AI intake assistant for law firms that asks the right questions, screens the lead and hands your team a clean case summary. Try the live demo free.";

const baseMetadata: Metadata = {
  title: TITLE,
  description: DESCRIPTION,
  alternates: { canonical: PAGE_URL },
  openGraph: { title: `${TITLE} | SearchPrex`, description: DESCRIPTION, url: PAGE_URL, siteName: "SearchPrex", type: "website", locale: "en_US" },
  twitter: { card: "summary_large_image", title: TITLE, description: DESCRIPTION },
};

// Metadata comes from the CMS row for this route; the object above is the
// fallback when that row is missing, unpublished, or the database is down.
export async function generateMetadata(): Promise<Metadata> {
  return getPageSEO("/intake-assistant", baseMetadata);
}

const DOES = [
  {
    icon: MessageSquareText,
    title: "Asks one question at a time",
    body: "It responds to what the person actually said, with empathy, and asks one short question at a time — the way a good intake specialist does, not a form with twenty fields.",
  },
  {
    icon: ClipboardList,
    title: "Gathers what the attorney needs",
    body: "What happened, when, the injuries and treatment, who was at fault, insurance, whether there is a police or incident report, whether another attorney is involved, and where it happened.",
  },
  {
    icon: Filter,
    title: "Screens the lead for your team",
    body: "Each conversation ends with an internal signal — qualified, needs review, or likely not viable — and a one-line reason, so your team knows which call to return first.",
  },
  {
    icon: ShieldCheck,
    title: "Stays inside the lines",
    body: "It never gives legal advice, filing deadlines or case values, never promises an outcome, and never tells someone they \"have a case\". It closes by saying the firm will follow up.",
  },
];

const SUMMARY_FIELDS = [
  ["Case type", "A short label, such as auto accident or slip and fall."],
  ["Incident date", "As the person stated it."],
  ["Overview", "Two or three plain-English sentences on what happened and the injuries."],
  ["Key facts", "The details your attorney would ask about first."],
  ["Screening signal", "Qualified, needs review, or likely not viable — with the reason. An internal signal, not a legal judgment."],
  ["Recommended next step", "For example, schedule a consultation within 24 hours."],
];

const FAQS = [
  {
    q: "What is an AI intake assistant for a law firm?",
    a: "It is a chat assistant on your website that talks to potential clients when your team cannot — evenings, weekends, busy afternoons. It asks about what happened, gathers the facts an attorney needs, and gives your firm a structured summary so someone can follow up quickly.",
  },
  {
    q: "Does the AI intake assistant give legal advice?",
    a: "No. It is built not to. It does not give legal advice, filing deadlines or case-value estimates, does not promise outcomes, and reminds the person that the conversation was information-gathering only. Your attorneys review and advise.",
  },
  {
    q: "Which practice areas does it handle?",
    a: "The demo on this page is set up for a personal injury firm. The assistant can be given a firm's own name and practice areas, so the questions fit the matters that firm takes.",
  },
  {
    q: "Does it replace our intake staff?",
    a: "No. It covers the moments nobody is available and does the first round of questions, so your staff start the follow-up call with the facts already written down.",
  },
  {
    q: "Does it answer phone calls?",
    a: "No. It is a chat assistant for your website. Phone calls still need a person or an answering service; the assistant covers the people who would rather type, or who visit when your office is closed.",
  },
  {
    q: "How do I get it on my firm's website?",
    a: "Try the demo above, then use the form at the end of the conversation, or ask for a free tear-down below. Setup depends on your site and practice areas, so it is scoped with you first.",
  },
];

export default function IntakeAssistantPage() {
  const jsonLd = {
    "@context": "https://schema.org",
    "@graph": [
      {
        "@type": "WebPage",
        "@id": `${PAGE_URL}#webpage`,
        url: PAGE_URL,
        name: TITLE,
        description: DESCRIPTION,
        inLanguage: "en-US",
        isPartOf: websiteRef,
        author: founderRef,
        primaryImageOfPage: { "@type": "ImageObject", url: OG_IMAGE },
      },
      {
        "@type": "WebApplication",
        "@id": `${PAGE_URL}#tool`,
        name: "SearchPrex AI Intake Assistant",
        applicationCategory: "BusinessApplication",
        operatingSystem: "Web",
        url: PAGE_URL,
        description:
          "An AI intake assistant for law firms that gathers a potential client's facts, screens the lead and produces a structured case summary for the firm.",
        offers: { "@type": "Offer", price: "0", priceCurrency: "USD", description: "Free live demo" },
        featureList: [
          "Conversational intake, one question at a time",
          "Incident, injury, fault, insurance and report details gathered",
          "Internal screening signal with a reason",
          "Structured case summary for the firm",
          "Configurable firm name and practice areas",
          "No legal advice, deadlines or case values",
        ],
        provider: organizationRef,
        audience: {
          "@type": "Audience",
          audienceType: "Law firms",
          geographicArea: { "@type": "Country", name: "United States" },
        },
        // No aggregateRating: there are no published reviews of the tool.
      },
      {
        "@type": "BreadcrumbList",
        itemListElement: [
          { "@type": "ListItem", position: 1, name: "Home", item: SITE },
          { "@type": "ListItem", position: 2, name: "AI Intake Assistant", item: PAGE_URL },
        ],
      },
      {
        "@type": "FAQPage",
        "@id": `${PAGE_URL}#faq`,
        mainEntity: FAQS.map((f) => ({ "@type": "Question", name: f.q, acceptedAnswer: { "@type": "Answer", text: f.a } })),
      },
    ],
  };

  const link = "font-semibold text-[#534AB7] underline underline-offset-2";

  return (
    <main id="main-content">
      <script id="ld-intake-assistant" type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(jsonLd) }} />

      <PageHero
        centered
        eyebrow="Law firm tool · Free live demo"
        title={
          <>
            AI intake assistant <Accent>for law firms</Accent>
          </>
        }
        subtitle="The person who finds your firm at 2 a.m. wants to tell someone what happened. This assistant listens, asks the questions an attorney would, and hands your team a clean case summary by morning. Try it below as if you were a potential client."
        trustPoints={["No legal advice given", "Screens every lead", "Built for US law firms"]}
      />

      {/* The demo itself — embedded, so the page keeps a single H1. */}
      <Section tight id="demo" width="reading">
        <IntakeAssistant embedded />
      </Section>

      <Section tone="surface">
        <SectionHeading
          eyebrow="What it does"
          title="What the AI intake assistant does"
          intro="Everything below is what the demo above actually does — nothing it can't."
        />
        <CardGrid columns={2}>
          {DOES.map((d) => (
            <FeatureCard key={d.title} icon={<d.icon className="h-5 w-5" style={{ color: "#534AB7" }} aria-hidden />} title={d.title} body={d.body} />
          ))}
        </CardGrid>
      </Section>

      <Section width="reading">
        <SectionHeading eyebrow="The handoff" title="What your firm receives from each conversation" />
        <dl className="divide-y divide-[#e5e7eb] rounded-2xl border border-[#e5e7eb] bg-white">
          {SUMMARY_FIELDS.map(([term, def]) => (
            <div key={term} className="grid gap-1 p-4 sm:grid-cols-[180px_1fr] sm:gap-4">
              <dt className="text-sm font-black text-[#0a0f2e]">{term}</dt>
              <dd className="text-sm leading-relaxed text-[#374151]">{def}</dd>
            </div>
          ))}
        </dl>
      </Section>

      <Section tone="surface" width="reading">
        <SectionHeading eyebrow="Why it matters" title="Ranking brings the enquiry. Intake decides whether it becomes a case." />
        <div className="space-y-4 text-base leading-relaxed text-[#374151]">
          <p>
            Most of the work in{" "}
            <Link href="/services/law-firm-seo" className={link}>
              law firm SEO
            </Link>{" "}
            goes into getting a firm found — the map pack, practice-area pages, AI answers. But someone who searched for an
            injury lawyer late at night is not going to wait until Monday. If nobody responds, they keep searching, and the
            next firm on the page gets the case.
          </p>
          <p>
            An intake assistant does not replace the call your team makes. It makes sure there is something to call back:
            the facts written down, the lead screened, and the next step clear. That is why it sits on our law firm pages
            next to the SEO work, not as a separate product.
          </p>
        </div>
      </Section>

      {/* Lead magnet — the softer offer for firms not ready to talk yet. */}
      <Section tight>
        <GuideMagnet guide={LAW_CHECKLIST_GUIDE} source="intake-assistant" eyebrow="Free for law firms" />
      </Section>

      <Section width="reading">
        <SectionHeading eyebrow="FAQ" title="AI intake assistant questions, answered" />
        <FaqList faqs={FAQS} name="intake-assistant-faq" />
      </Section>

      <ArticleLeadMagnet
        variant="bottom"
        source="intake-assistant"
        copy={{
          headline: "Want more enquiries worth answering? Send me your firm's URL.",
          sub: "I'll check your practice-area pages, Business Profile and the firms outranking you, and send back what to fix first — within 24 hours.",
        }}
      />
    </main>
  );
}
