// app/services/ecommerce-seo/page.tsx
// Server Component. Owns metadata (canonical, Open Graph, Twitter Card)
// and JSON-LD (Service + BreadcrumbList + FAQPage). The interactive UI
// lives in EcommerceSEOClient (a client island).
 
import type { Metadata } from "next";
import EcommerceSEOClient from "./EcommerceSEOClient";
import { CAPSULES, FAQS } from "./data";
import { founderRef, organizationRef, websiteRef } from "@/lib/site-schema";
import { RETAINER_PLANS } from "@/lib/pricing";
 
import { getPageSEO } from "@/lib/admin-seo";
const SITE = "https://www.searchprex.com";
const PAGE_URL = `${SITE}/services/ecommerce-seo`;
// No OG_IMAGE constant. This pointed at /images/og-ecommerce-seo.jpg, a file
// that never existed, so every share of this page showed a broken image.
// The card is now generated by ./opengraph-image.tsx, like the other services.
 
const baseMetadata: Metadata = {
  title: "Ecommerce SEO Services — Fix Indexing & Grow Revenue",
  description:
    "Founder-led ecommerce SEO for Shopify and WooCommerce stores: indexing recovery, product and category content, Core Web Vitals. SMK Store went from $5,832 to $19,100 a month.",
  alternates: {
    canonical: PAGE_URL,
  },
  openGraph: {
    title: "Ecommerce SEO Services — Fix Indexing & Grow Revenue | SearchPrex",
    description:
      "Founder-led ecommerce SEO for Shopify and WooCommerce stores. Fix mass non-indexing, thin content, and Core Web Vitals — verified Google Search Console results.",
    url: PAGE_URL,
    siteName: "SearchPrex",
    type: "website",
  },
  twitter: {
    card: "summary_large_image",
    title: "Ecommerce SEO Services — Fix Indexing & Grow Revenue | SearchPrex",
    description:
      "Founder-led ecommerce SEO for Shopify and WooCommerce stores. Verified Google Search Console results — no vanity metrics.",
  },
};

// Metadata comes from the CMS row for this route; the object above is the
// fallback when that row is missing, unpublished, or the database is down.
export async function generateMetadata(): Promise<Metadata> {
  return getPageSEO("/services/ecommerce-seo", baseMetadata);
}
 
/**
 * When this page was last reviewed by a person. Hardcoded on purpose — a date
 * that moves on every request claims a review that did not happen.
 */
const LAST_REVIEWED = "2026-09-26";
const ECOM_PLAN = RETAINER_PLANS.find((p) => p.niche === "Ecommerce SEO");

export default function Page() {
  // Built from ./data (what the page renders) and the site-wide entities by
  // @id. The FAQPage used to list six questions that were not the page's six
  // questions — structured data describing content no visitor could see.
  const jsonLd = {
    "@context": "https://schema.org",
    "@graph": [
      {
        "@type": "WebPage",
        "@id": `${PAGE_URL}#webpage`,
        url: PAGE_URL,
        name: "Ecommerce SEO Services",
        isPartOf: websiteRef,
        about: { "@id": `${PAGE_URL}#service` },
        author: founderRef,
        reviewedBy: founderRef,
        dateModified: LAST_REVIEWED,
      },
      {
        "@type": "Service",
        "@id": `${PAGE_URL}#service`,
        name: "Ecommerce SEO Services",
        serviceType: "Ecommerce SEO",
        provider: organizationRef,
        areaServed: { "@type": "Country", name: "United States" },
        audience: { "@type": "BusinessAudience", audienceType: "Shopify, WooCommerce and custom ecommerce stores" },
        description:
          "Ecommerce SEO: indexing recovery at catalogue scale, product and category page content, structured data, and Core Web Vitals for Shopify, WooCommerce and custom stores.",
        url: PAGE_URL,
        ...(ECOM_PLAN
          ? {
              offers: {
                "@type": "Offer",
                priceSpecification: {
                  "@type": "UnitPriceSpecification",
                  minPrice: ECOM_PLAN.min,
                  maxPrice: ECOM_PLAN.max,
                  priceCurrency: "USD",
                  unitText: "MONTH",
                },
              },
            }
          : {}),
      },
      {
        "@type": "BreadcrumbList",
        itemListElement: [
          { "@type": "ListItem", position: 1, name: "Home", item: SITE },
          { "@type": "ListItem", position: 2, name: "Services", item: `${SITE}/services` },
          { "@type": "ListItem", position: 3, name: "Ecommerce SEO", item: PAGE_URL },
        ],
      },
      {
        "@type": "FAQPage",
        "@id": `${PAGE_URL}#faq`,
        mainEntity: [...CAPSULES, ...FAQS].map((f) => ({
          "@type": "Question",
          name: f.q,
          acceptedAnswer: { "@type": "Answer", text: f.a },
        })),
      },
    ],
  };

  return (
    <>
      <script id="ld-ecommerce-seo" type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(jsonLd) }} />
      {/* Required prop that was never passed, so the AuthorCard rendered without
          its LinkedIn link — a missing E-E-A-T signal on a page whose whole
          argument is verifiable, founder-led work. */}
      <EcommerceSEOClient linkedinUrl="https://www.linkedin.com/in/mubashar-sharif-senior-seo-analyst/" />
    </>
  );
}
