import type { Metadata } from "next";
import LocalSEOClient from "./LocalSEOClient";
import { CAPSULES, FAQS } from "./data";
import { founderRef, organizationRef, websiteRef } from "@/lib/site-schema";
import { RETAINER_PLANS } from "@/lib/pricing";

import { getPageSEO } from "@/lib/admin-seo";
const PAGE_URL = "https://www.searchprex.com/services/local-seo";
// No OG_IMAGE constant: the card is generated by ./opengraph-image.tsx, which
// Next wires into this route automatically. The URL that used to sit here
// pointed into public/og/, a directory that has never existed in this repo.

const baseMetadata: Metadata = {
  title: "Local SEO Services | Own the Map Pack & AI Overviews",
  description:
    "Founder-led local SEO that puts your business in the top 3 Google Maps pack and 2026 AI Overviews. GBP optimization, citations, review velocity, and city-level landing pages.",
  keywords: [
    "local SEO services", "Google Maps SEO", "GBP optimization",
    "local pack ranking", "near me SEO", "AI Overview local SEO",
  ],
  alternates: { canonical: PAGE_URL },
  openGraph: {
    title: "Local SEO Services | SearchPrex",
    description:
      "Rank in the Google Maps top 3 and get cited in AI Overviews for local queries. Founder-led local SEO for service businesses.",
    url: PAGE_URL,
    siteName: "SearchPrex",
    type: "website",
  },
  twitter: {
    card: "summary_large_image",
    title: "Local SEO Services | SearchPrex",
    description: "Top 3 map pack + AI Overview visibility. Founder-led local SEO.",
  },
  robots: { index: true, follow: true, googleBot: { index: true, follow: true, "max-image-preview": "large", "max-snippet": -1 } },
};

// Metadata comes from the CMS row for this route; the object above is the
// fallback when that row is missing, unpublished, or the database is down.
export async function generateMetadata(): Promise<Metadata> {
  return getPageSEO("/services/local-seo", baseMetadata);
}

/**
 * When this page was last reviewed by a person. Hardcoded on purpose — a date
 * that moves on every request claims a review that did not happen.
 */
const LAST_REVIEWED = "2026-09-26";
const LOCAL_PLAN = RETAINER_PLANS.find((p) => p.niche === "Local SEO");

export default function LocalSEOPage() {
  // Built from ./data (what the page renders) and the site-wide entities by
  // @id. The FAQPage used to be typed here by hand — three of six questions.
  const jsonLd = {
    "@context": "https://schema.org",
    "@graph": [
      {
        "@type": "WebPage",
        "@id": `${PAGE_URL}#webpage`,
        url: PAGE_URL,
        name: "Local SEO Services",
        isPartOf: websiteRef,
        about: { "@id": `${PAGE_URL}#service` },
        author: founderRef,
        reviewedBy: founderRef,
        dateModified: LAST_REVIEWED,
      },
      {
        "@type": "Service",
        "@id": `${PAGE_URL}#service`,
        name: "Local SEO Services",
        serviceType: "Local SEO",
        provider: organizationRef,
        areaServed: { "@type": "Country", name: "United States" },
        description:
          "Google Business Profile optimisation, citation and NAP consistency, service-area pages, a review program, and AI Overview readiness for local service businesses.",
        url: PAGE_URL,
        ...(LOCAL_PLAN
          ? {
              offers: {
                "@type": "Offer",
                priceSpecification: {
                  "@type": "UnitPriceSpecification",
                  minPrice: LOCAL_PLAN.min,
                  maxPrice: LOCAL_PLAN.max,
                  priceCurrency: "USD",
                  unitText: "MONTH",
                },
              },
            }
          : {}),
      },
      {
        "@type": "BreadcrumbList",
        itemListElement: [
          { "@type": "ListItem", position: 1, name: "Home", item: "https://www.searchprex.com" },
          { "@type": "ListItem", position: 2, name: "Services", item: "https://www.searchprex.com/services" },
          { "@type": "ListItem", position: 3, name: "Local SEO", item: PAGE_URL },
        ],
      },
      {
        "@type": "FAQPage",
        "@id": `${PAGE_URL}#faq`,
        mainEntity: [...CAPSULES, ...FAQS].map((f) => ({
          "@type": "Question",
          name: f.q,
          acceptedAnswer: { "@type": "Answer", text: f.a },
        })),
      },
    ],
  };

  return (
    <>
      <script id="ld-local-seo" type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(jsonLd) }} />
      <LocalSEOClient />
    </>
  );
}
