import type { Metadata } from "next";
import TechnicalSEOClient from "./TechnicalSEOClient";
import { CAPSULES, FAQS } from "./data";
import { founderRef, organizationRef, websiteRef } from "@/lib/site-schema";

import { getPageSEO } from "@/lib/admin-seo";
const PAGE_URL = "https://www.searchprex.com/services/technical-seo";
// No OG_IMAGE constant: the card is generated by ./opengraph-image.tsx, which
// Next wires into this route automatically. The URL that used to sit here
// pointed into public/og/, a directory that has never existed in this repo.

const baseMetadata: Metadata = {
  title: "Technical SEO Services | Indexation, Core Web Vitals, Schema",
  description:
    "Founder-led technical SEO: indexation recovery, crawl budget, Core Web Vitals and schema. Michigan Outdoor Sports went from about 3,000 to 11,549 indexed pages.",
  keywords: [
    "technical SEO services", "Core Web Vitals optimization", "indexation recovery",
    "schema markup", "crawl budget", "site architecture SEO", "INP optimization",
  ],
  alternates: { canonical: PAGE_URL },
  openGraph: {
    title: "Technical SEO Services | SearchPrex",
    description:
      "Recover mass non-indexing, fix Core Web Vitals, and structure your site for Google's 2026 algorithm. +285% pages indexed and +83% US clicks on Michigan Outdoor Sports, rebuilt after a de-indexing.",
    url: PAGE_URL,
    siteName: "SearchPrex",
    type: "website",
  },
  twitter: {
    card: "summary_large_image",
    title: "Technical SEO Services | SearchPrex",
    description: "Indexation recovery, crawl budget, Core Web Vitals and schema — about 3,000 to 11,549 indexed pages on one store.",
  },
  robots: { index: true, follow: true, googleBot: { index: true, follow: true, "max-image-preview": "large", "max-snippet": -1 } },
};

// Metadata comes from the CMS row for this route; the object above is the
// fallback when that row is missing, unpublished, or the database is down.
export async function generateMetadata(): Promise<Metadata> {
  return getPageSEO("/services/technical-seo", baseMetadata);
}

/**
 * When this page was last reviewed by a person. Hardcoded on purpose: a
 * "reviewed" date that moves on every request claims a check that did not
 * happen. Change it when the page is actually reviewed.
 */
const LAST_REVIEWED = "2026-09-26";

export default function TechnicalSEOPage() {
  // Every node is built from the data the page renders (./data) or refers to
  // the site-wide entities by @id — never retyped. The FAQPage used to be
  // written out here by hand: three of the six visible questions, with answers
  // that had drifted from the ones on the page.
  const jsonLd = {
    "@context": "https://schema.org",
    "@graph": [
      {
        "@type": "WebPage",
        "@id": `${PAGE_URL}#webpage`,
        url: PAGE_URL,
        name: "Technical SEO Services",
        isPartOf: websiteRef,
        about: { "@id": `${PAGE_URL}#service` },
        author: founderRef,
        reviewedBy: founderRef,
        dateModified: LAST_REVIEWED,
      },
      {
        "@type": "Service",
        "@id": `${PAGE_URL}#service`,
        name: "Technical SEO Services",
        serviceType: "Technical SEO",
        provider: organizationRef,
        areaServed: { "@type": "Country", name: "United States" },
        description:
          "Indexation recovery, crawl budget, Core Web Vitals (LCP, INP, CLS), structured data, site architecture, redirects and migrations.",
        url: PAGE_URL,
      },
      {
        "@type": "BreadcrumbList",
        itemListElement: [
          { "@type": "ListItem", position: 1, name: "Home", item: "https://www.searchprex.com" },
          { "@type": "ListItem", position: 2, name: "Services", item: "https://www.searchprex.com/services" },
          { "@type": "ListItem", position: 3, name: "Technical SEO", item: PAGE_URL },
        ],
      },
      {
        "@type": "FAQPage",
        "@id": `${PAGE_URL}#faq`,
        mainEntity: [...CAPSULES, ...FAQS].map((f) => ({
          "@type": "Question",
          name: f.q,
          acceptedAnswer: { "@type": "Answer", text: f.a },
        })),
      },
    ],
  };

  return (
    <>
      <script id="ld-technical-seo" type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(jsonLd) }} />
      <TechnicalSEOClient />
    </>
  );
}
