import type { Metadata } from "next";
import Script from "next/script";
import AIToolClient from "./AIToolClient";

import { getPageSEO } from "@/lib/admin-seo";
const PAGE_URL = "https://www.searchprex.com/ai-search";

// The OG image is generated by ./opengraph-image.tsx, which Next wires into the
// route's metadata automatically. It used to be a hardcoded /og/ai-search.jpg —
// a file that has never existed in public/, so every share of this page since
// launch has rendered a blank card. Nothing here should name that path again.

// What this page ACTUALLY is: a free-form SEO question answering engine. Every
// string below has to describe that. The previous copy described a URL-input
// audit tool that returns a 0-100 score, Core Web Vitals, and a backlink
// profile — none of which exists here or ever did. Searchers arriving on that
// promise found a single question box and left.
const baseMetadata: Metadata = {
  title: "Ask Any SEO Question — Free AI SEO Answer Engine",
  description:
    "Ask any SEO question and get an instant AI answer grounded in live Google Search results, with sources. Built for US law firms, ecommerce stores & local businesses. Free, no login.",
  keywords: [
    "AI SEO answer engine",
    "ask AI SEO questions",
    "free SEO answers",
    "AI SEO assistant",
    "SEO questions answered",
    "law firm SEO questions",
    "ecommerce SEO questions",
    "local SEO questions",
  ],
  alternates: {
    canonical: PAGE_URL,
  },
  openGraph: {
    title: "Ask Any SEO Question — Free AI SEO Answer Engine | SearchPrex",
    description:
      "Instant, source-cited AI answers to any SEO question — grounded in live Google Search. Tuned for law firms, ecommerce stores, and local businesses across the US.",
    url: PAGE_URL,
    siteName: "SearchPrex",
    type: "website",
    locale: "en_US",
  },
  twitter: {
    card: "summary_large_image",
    title: "Ask Any SEO Question — Free AI SEO Answer Engine | SearchPrex",
    description:
      "Instant, source-cited AI answers to any SEO question. Free, no login.",
  },
  robots: {
    index: true,
    follow: true,
    googleBot: {
      index: true,
      follow: true,
      "max-image-preview": "large",
      "max-snippet": -1,
      "max-video-preview": -1,
    },
  },
  // The `geo.region` / `geo.placename` pair that used to live here was dropped.
  // Google has not consumed geo meta tags for over a decade; `locale: en_US`
  // above and the en-US alternates that getPageSEO adds are the signals that
  // actually carry. Keeping dead tags around invites someone to "fix" US
  // targeting by editing them.
};

// Metadata comes from the CMS row for this route; the object above is the
// fallback when that row is missing, unpublished, or the database is down.
//
// NOTE: a *published* Page row exists for /ai-search and its `title` and
// `metaDescription` still hold the old audit-tool copy. getPageSEO lets a
// non-empty CMS field win, so those two fields override what is written above
// until the row is updated in the admin panel. Every other field here —
// openGraph, twitter, keywords, robots — is null in that row and ships from
// this file.
export async function generateMetadata(): Promise<Metadata> {
  return getPageSEO("/ai-search", baseMetadata);
}

export default function AISearchPage() {
  const jsonLd = {
    "@context": "https://schema.org",
    "@graph": [
      {
        "@type": "WebPage",
        "@id": `${PAGE_URL}#webpage`,
        url: PAGE_URL,
        name: "Ask Any SEO Question — Free AI SEO Answer Engine",
        description:
          "A free AI answer engine for SEO questions. Ask anything about SEO and get an instant answer grounded in live Google Search results, with the sources it drew on.",
        inLanguage: "en-US",
        isPartOf: {
          "@type": "WebSite",
          "@id": "https://www.searchprex.com/#website",
          url: "https://www.searchprex.com",
          name: "SearchPrex",
        },
      },
      {
        "@type": "WebApplication",
        "@id": `${PAGE_URL}#tool`,
        name: "SearchPrex AI — SEO Answer Engine",
        applicationCategory: "SEOApplication",
        operatingSystem: "Web",
        url: PAGE_URL,
        description:
          "Ask a free-form SEO question and get an AI-generated answer grounded in live Google Search results, with cited sources and links to relevant SearchPrex resources.",
        offers: {
          "@type": "Offer",
          price: "0",
          priceCurrency: "USD",
        },
        // Every entry below is a capability app/api/seo-search/route.ts really
        // implements. The list this replaced advertised an SEO score out of
        // 100, Core Web Vitals analysis, a schema audit, a backlink check, a
        // mobile UX evaluation, and a 90-day roadmap — six features this page
        // has no code for. Structured data that describes a different product
        // than the page is a Google spam-policy violation, not just noise.
        featureList: [
          "Answers any free-form SEO question",
          "Grounded in live Google Search results",
          "Cites the web sources behind each answer",
          "Detects your vertical: law firm, ecommerce, or local",
          "Links to relevant SearchPrex guidance",
          "No login, signup, or credit card",
        ],
        provider: {
          "@type": "Organization",
          name: "SearchPrex",
          url: "https://www.searchprex.com",
        },
        // No `aggregateRating` here, deliberately. The removed block claimed
        // 4.9 from 20 reviews while the page shows no rating and no review.
        // Google requires a rating in structured data to be visible on the page
        // and to be about the item — an invisible one risks a manual action.
        // If real reviews are collected later, render them before marking
        // them up.
      },
      {
        "@type": "BreadcrumbList",
        itemListElement: [
          { "@type": "ListItem", position: 1, name: "Home", item: "https://www.searchprex.com" },
          { "@type": "ListItem", position: 2, name: "AI Search", item: PAGE_URL },
        ],
      },
      // The FAQPage block is gone for now. Its five Q&As all described the
      // audit tool ("Enter your URL and get results in seconds"), and none of
      // them appeared anywhere on the page. FAQ markup has to correspond to
      // FAQ content the visitor can actually see. It comes back with the
      // visible FAQ section, not before.
    ],
  };

  return (
    <>
      <Script
        id="ld-ai-search"
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(jsonLd) }}
      />
      <AIToolClient />
    </>
  );
}
