import type { Metadata } from "next";
import Link from "next/link";
import AiSearch from "@/app/components/ai-search/ai-search";
import ArticleLeadMagnet from "@/components/ArticleLeadMagnet";
import { CardGrid, FaqList, FeatureCard, Section, SectionHeading } from "@/components/layout";

const STEPS = [
  { step: "01", title: "Ask in plain English", body: "Type the question the way you would ask a colleague — about your law firm, your store or your local business." },
  { step: "02", title: "Get a straight answer", body: "The answer comes back in plain English, tuned to the kind of business the question is about, with links to the SearchPrex guides that go deeper." },
  { step: "03", title: "Know where it came from", body: "When live Google Search checking is available, the answer is checked against it and says so. Otherwise it is labelled as general SEO knowledge, not live search." },
];

const GUIDES = [
  { href: "/services/law-firm-seo", title: "Law firm SEO", body: "Practice-area pages, the map pack and bar rules." },
  { href: "/blog/keyword-research-for-law-firms", title: "Keyword research for law firms", body: "An eight-step method using free data." },
  { href: "/services/local-seo", title: "Local SEO", body: "Business Profile, reviews and service-area pages." },
  { href: "/resources/google-business-profile-checklist", title: "Business Profile checklist", body: "23 checks, written to Google's rules." },
  { href: "/services/ecommerce-seo", title: "Ecommerce SEO", body: "Indexing and product content for large catalogues." },
  { href: "/resources/woocommerce-seo-checklist", title: "WooCommerce SEO checklist", body: "25 checks from real store recoveries." },
  { href: "/resources/technical-seo-checklist", title: "Technical SEO checklist", body: "26 checks you can run with free Google tools." },
  { href: "/resources/news", title: "SEO news", body: "Google updates, dated and sourced." },
];

const FAQS = [
  {
    q: "Is the AI SEO answer engine free?",
    a: "Yes. There is no login, signup or credit card. Ask as many SEO questions as you like.",
  },
  {
    q: "Where do the answers come from?",
    a: "From an AI model given SEO guidance for law firms, ecommerce stores and local businesses. When live Google Search checking is available the answer is checked against it and labelled that way; otherwise it is labelled as general SEO knowledge, not live search.",
  },
  {
    q: "Can it check my website or my rankings?",
    a: "No. It answers questions; it does not crawl your site or look up your positions. For a specific site, use the SERP checker or ask for the free tear-down, where I review your site myself.",
  },
  {
    q: "How accurate are the answers?",
    a: "They are general guidance and can be incomplete or out of date, like any AI answer. Check anything important against Google's own documentation, and treat the answer as a starting point rather than a decision.",
  },
  {
    q: "What happens to the question I type?",
    a: "It is sent to the AI model to generate the answer and is not saved by SearchPrex. Your details are only stored if you choose to fill in the form after an answer.",
  },
];

import { getPageSEO } from "@/lib/admin-seo";
const PAGE_URL = "https://www.searchprex.com/ai-search";

// The OG image is generated by ./opengraph-image.tsx, which Next wires into the
// route's metadata automatically. It used to be a hardcoded /og/ai-search.jpg —
// a file that has never existed in public/, so every share of this page since
// launch has rendered a blank card. Nothing here should name that path again.

// What this page ACTUALLY is: a free-form SEO question answering engine. Every
// string below has to describe that. The previous copy described a URL-input
// audit tool that returns a 0-100 score, Core Web Vitals, and a backlink
// profile — none of which exists here or ever did. Searchers arriving on that
// promise found a single question box and left.
const baseMetadata: Metadata = {
  title: "Free AI SEO Answer Engine: Ask Any Question",
  description:
    "Ask any SEO question and get an instant, plain-English AI answer tuned for US law firms, ecommerce stores & local businesses. Free, no login.",
  keywords: [
    "AI SEO answer engine",
    "ask AI SEO questions",
    "free SEO answers",
    "AI SEO assistant",
    "SEO questions answered",
    "law firm SEO questions",
    "ecommerce SEO questions",
    "local SEO questions",
  ],
  alternates: {
    canonical: PAGE_URL,
  },
  openGraph: {
    title: "Free AI SEO Answer Engine: Ask Any Question | SearchPrex",
    description:
      "Instant AI answers to any SEO question, tuned for law firms, ecommerce stores, and local businesses across the US.",
    url: PAGE_URL,
    siteName: "SearchPrex",
    type: "website",
    locale: "en_US",
  },
  twitter: {
    card: "summary_large_image",
    title: "Free AI SEO Answer Engine: Ask Any Question | SearchPrex",
    description:
      "Instant AI answers to any SEO question. Free, no login.",
  },
  robots: {
    index: true,
    follow: true,
    googleBot: {
      index: true,
      follow: true,
      "max-image-preview": "large",
      "max-snippet": -1,
      "max-video-preview": -1,
    },
  },
  // The `geo.region` / `geo.placename` pair that used to live here was dropped.
  // Google has not consumed geo meta tags for over a decade; `locale: en_US`
  // above and the en-US alternates that getPageSEO adds are the signals that
  // actually carry. Keeping dead tags around invites someone to "fix" US
  // targeting by editing them.
};

// Metadata comes from the CMS row for this route; the object above is the
// fallback when that row is missing, unpublished, or the database is down.
//
// NOTE: a *published* Page row exists for /ai-search, and getPageSEO lets a
// non-empty CMS field win, so the row's `title` and `metaDescription` override
// what is written above. Both were corrected to match this file by
// scripts/fix-ai-search-seo.ts. Every other field here — openGraph, twitter,
// keywords, robots — is null in that row and ships from this file.
//
// This route is statically prerendered and exports no `revalidate`, so the
// getPageSEO read below happens at BUILD time. Changing the CMS row — here or
// in /admin/pages — has no effect on the live page until the next deploy.
export async function generateMetadata(): Promise<Metadata> {
  return getPageSEO("/ai-search", baseMetadata);
}

export default function AISearchPage() {
  const jsonLd = {
    "@context": "https://schema.org",
    "@graph": [
      {
        "@type": "WebPage",
        "@id": `${PAGE_URL}#webpage`,
        url: PAGE_URL,
        name: "Free AI SEO Answer Engine: Ask Any Question",
        description:
          "A free AI answer engine for SEO questions. Ask anything about SEO and get an instant, plain-English answer.",
        inLanguage: "en-US",
        isPartOf: {
          "@type": "WebSite",
          "@id": "https://www.searchprex.com/#website",
          url: "https://www.searchprex.com",
          name: "SearchPrex",
        },
      },
      {
        "@type": "WebApplication",
        "@id": `${PAGE_URL}#tool`,
        name: "SearchPrex AI — SEO Answer Engine",
        applicationCategory: "SEOApplication",
        operatingSystem: "Web",
        url: PAGE_URL,
        description:
          "Ask a free-form SEO question and get an AI-generated answer, with links to relevant SearchPrex resources.",
        offers: {
          "@type": "Offer",
          price: "0",
          priceCurrency: "USD",
        },
        // Every entry below is a capability app/api/seo-search/route.ts really
        // implements. The list this replaced advertised an SEO score out of
        // 100, Core Web Vitals analysis, a schema audit, a backlink check, a
        // mobile UX evaluation, and a 90-day roadmap — six features this page
        // has no code for. Structured data that describes a different product
        // than the page is a Google spam-policy violation, not just noise.
        featureList: [
          "Answers any free-form SEO question",
         "Detects your vertical: law firm, ecommerce, or local",
          "Links to relevant SearchPrex guidance",
          "No login, signup, or credit card",
        ],
        provider: {
          "@type": "Organization",
          name: "SearchPrex",
          url: "https://www.searchprex.com",
        },
        // No `aggregateRating` here, deliberately. The removed block claimed
        // 4.9 from 20 reviews while the page shows no rating and no review.
        // Google requires a rating in structured data to be visible on the page
        // and to be about the item — an invisible one risks a manual action.
        // If real reviews are collected later, render them before marking
        // them up.
      },
      {
        "@type": "BreadcrumbList",
        itemListElement: [
          { "@type": "ListItem", position: 1, name: "Home", item: "https://www.searchprex.com" },
          { "@type": "ListItem", position: 2, name: "AI Search", item: PAGE_URL },
        ],
      },
      // Built from the FAQ rendered below, so the markup matches what a
      // visitor can read.
      {
        "@type": "FAQPage",
        "@id": `${PAGE_URL}#faq`,
        mainEntity: FAQS.map((f) => ({ "@type": "Question", name: f.q, acceptedAnswer: { "@type": "Answer", text: f.a } })),
      },
    ],
  };

  const link = "text-sm font-black text-[#0a0f2e] group-hover:text-[#534AB7]";

  return (
    <main id="main-content" className="bg-[#f8f9fc] pt-20">
      <script
        id="ld-ai-search"
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(jsonLd) }}
      />
      <div className="mx-auto max-w-4xl px-4 sm:px-6 lg:px-8">
        <AiSearch />
      </div>

      <Section>
        <SectionHeading eyebrow="How it works" title="How the AI SEO answer engine works" />
        <CardGrid columns={3}>
          {STEPS.map((st) => (
            <FeatureCard key={st.step} step={st.step} title={st.title} body={st.body} />
          ))}
        </CardGrid>
      </Section>

      <Section tone="surface">
        <SectionHeading eyebrow="Use it well" title="What it is good for — and what it isn't" />
        <CardGrid columns={2}>
          <FeatureCard
            title="Good for"
            body="Strategy questions, how a Google feature works, what to fix first on a type of site, and explaining SEO terms in plain English — for law firms, stores and local businesses in the US."
          />
          <FeatureCard
            title="Not for"
            body="Your live rankings or traffic, anything that needs your own analytics, legal or financial advice, and guarantees. For your specific site, the free tear-down below is the right tool."
          />
        </CardGrid>
      </Section>

      <Section>
        <SectionHeading eyebrow="Go deeper" title="Guides and free checklists" intro="The pages the answers most often point to." />
        <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4">
          {GUIDES.map((g) => (
            <Link
              key={g.href}
              href={g.href}
              className="group rounded-2xl border border-[#e5e7eb] bg-white p-5 transition-all hover:border-[#534AB7] hover:shadow-md"
            >
              <p className={link}>{g.title}</p>
              <p className="mt-1.5 text-xs leading-relaxed text-[#5b6472]">{g.body}</p>
            </Link>
          ))}
        </div>
      </Section>

      <Section tone="surface" width="reading">
        <SectionHeading eyebrow="FAQ" title="AI SEO answer engine questions, answered" />
        <FaqList faqs={FAQS} name="ai-search-faq" />
      </Section>

      <ArticleLeadMagnet
        variant="bottom"
        source="ai-search"
        copy={{
          headline: "Want an answer about your own site? Send me your URL.",
          sub: "A written look at your site, your Business Profile and the competitors above you — from me, within 24 hours.",
        }}
      />
    </main>
  );
}
