import type { Metadata } from "next";
import LawFirmSEOClient from "./LawFirmSEOClient";
import { CAPSULES, FAQS } from "./data";
import { founderRef, organizationRef, websiteRef } from "@/lib/site-schema";
import { RETAINER_PLANS } from "@/lib/pricing";

import { getPageSEO } from "@/lib/admin-seo";
const PAGE_URL = "https://www.searchprex.com/services/law-firm-seo";
// No OG_IMAGE constant: the card is generated by ./opengraph-image.tsx, which
// Next wires into this route automatically. The URL that used to sit here
// pointed into public/og/, a directory that has never existed in this repo.

const baseMetadata: Metadata = {
  title: "Law Firm SEO Services | Rank in Local Pack & AI Overviews",
  description:
    "Founder-led SEO for law firms. Attorney E-E-A-T content, practice area pages, local pack rankings, and AI Overview citations — replace expensive Google Ads with organic cases.",
  keywords: [
    "law firm SEO", "attorney SEO", "legal SEO services",
    "law firm local SEO", "attorney AI Overview", "YMYL legal content",
  ],
  alternates: { canonical: PAGE_URL },
  openGraph: {
    title: "Law Firm SEO Services | SearchPrex",
    description:
      "Practice-area pages, local map pack work and AI Overview-ready answers for law firms. Founder-led SEO built for YMYL legal content — no ranking promises.",
    url: PAGE_URL,
    siteName: "SearchPrex",
    type: "website",
  },
  twitter: {
    card: "summary_large_image",
    title: "Law Firm SEO Services | SearchPrex",
    description: "Map pack + AI Overview citations for law firms. Founder-led, YMYL-aligned.",
  },
  robots: { index: true, follow: true, googleBot: { index: true, follow: true, "max-image-preview": "large", "max-snippet": -1 } },
};

// Metadata comes from the CMS row for this route; the object above is the
// fallback when that row is missing, unpublished, or the database is down.
export async function generateMetadata(): Promise<Metadata> {
  return getPageSEO("/services/law-firm-seo", baseMetadata);
}

/**
 * When this page was last reviewed by a person. Hardcoded on purpose — a date
 * that moves on every request claims a review that did not happen.
 */
const LAST_REVIEWED = "2026-09-26";
const LAW_PLAN = RETAINER_PLANS.find((p) => p.niche === "Law Firm SEO");

export default function LawFirmSEOPage() {
  // Built from ./data (what the page renders) and the site-wide entities by
  // @id. The FAQPage used to be typed here by hand — three of six questions,
  // including "Most law firms see ranking improvements in 30–60 days".
  const jsonLd = {
    "@context": "https://schema.org",
    "@graph": [
      {
        "@type": "WebPage",
        "@id": `${PAGE_URL}#webpage`,
        url: PAGE_URL,
        name: "Law Firm SEO Services",
        isPartOf: websiteRef,
        about: { "@id": `${PAGE_URL}#service` },
        author: founderRef,
        reviewedBy: founderRef,
        dateModified: LAST_REVIEWED,
      },
      {
        "@type": "Service",
        "@id": `${PAGE_URL}#service`,
        name: "Law Firm SEO Services",
        serviceType: "Law Firm SEO",
        provider: organizationRef,
        areaServed: { "@type": "Country", name: "United States" },
        audience: { "@type": "BusinessAudience", audienceType: "Law firms" },
        description:
          "SEO for law firms: practice-area and city pages, Google Business Profile, attorney E-E-A-T, technical SEO and AI Overview readiness, built to legal YMYL standards.",
        url: PAGE_URL,
        ...(LAW_PLAN
          ? {
              offers: {
                "@type": "Offer",
                priceSpecification: {
                  "@type": "UnitPriceSpecification",
                  minPrice: LAW_PLAN.min,
                  maxPrice: LAW_PLAN.max,
                  priceCurrency: "USD",
                  unitText: "MONTH",
                },
              },
            }
          : {}),
      },
      {
        "@type": "BreadcrumbList",
        itemListElement: [
          { "@type": "ListItem", position: 1, name: "Home", item: "https://www.searchprex.com" },
          { "@type": "ListItem", position: 2, name: "Services", item: "https://www.searchprex.com/services" },
          { "@type": "ListItem", position: 3, name: "Law Firm SEO", item: PAGE_URL },
        ],
      },
      {
        "@type": "FAQPage",
        "@id": `${PAGE_URL}#faq`,
        mainEntity: [...CAPSULES, ...FAQS].map((f) => ({
          "@type": "Question",
          name: f.q,
          acceptedAnswer: { "@type": "Answer", text: f.a },
        })),
      },
    ],
  };

  return (
    <>
      <script id="ld-law-firm-seo" type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(jsonLd) }} />
      <LawFirmSEOClient />
    </>
  );
}
