// lib/gsc-regex-data.ts
//
// Battle-tested RE2 regular expressions for Google Search Console (Performance >
// Search results > + New > Query / Page > Custom (regex)).
//
// Google Search Console uses RE2 syntax — no lookaheads (?=...) or lookbehinds.
// Every pattern below is strictly valid RE2 and tested in real client properties.

export type RegexCategory =
  | "ai-aeo"
  | "law-firm"
  | "ecommerce"
  | "technical-urls"
  | "local-seo"
  | "questions-intent";

export interface GscRegexPattern {
  id: string;
  title: string;
  category: RegexCategory;
  filterTarget: "Query" | "Page";
  matchMode: "Matches regex" | "Doesn't match regex";
  regex: string;
  whatItFinds: string;
  actionToTake: string;
  exampleMatch: string;
}

export const REGEX_CATEGORIES: Array<{
  id: RegexCategory | "all";
  label: string;
  count?: number;
}> = [
  { id: "all", label: "All Patterns" },
  { id: "ai-aeo", label: "AI Overviews & AEO" },
  { id: "law-firm", label: "Law Firm SEO" },
  { id: "ecommerce", label: "Ecommerce & WooCommerce" },
  { id: "technical-urls", label: "Technical & Indexing URLs" },
  { id: "local-seo", label: "Local SEO & Map Pack" },
  { id: "questions-intent", label: "Questions & Buyer Intent" },
];

export const GSC_REGEX_PATTERNS: GscRegexPattern[] = [
  // ── 1. AI Overviews & AEO (Conversational & Prompt-Style Queries) ──────────
  {
    id: "ai-8-plus-words",
    title: "8+ Word Conversational / AI-Prompt Queries",
    category: "ai-aeo",
    filterTarget: "Query",
    matchMode: "Matches regex",
    regex: "^([^\" \"]+\\s){7,}[^\" \"]+$",
    whatItFinds:
      "Long-tail, conversational searches (8 or more words) where Google almost always triggers an AI Overview or where users paste full prompts into Search.",
    actionToTake:
      "Sort by Impressions descending. Add a 40–60 word direct answer paragraph immediately under an H2 matching the top query to win the AI Overview citation.",
    exampleMatch: "what is the statute of limitations for car accidents in texas",
  },
  {
    id: "ai-10-plus-words",
    title: "10+ Word Ultra-Specific Prompt Queries (Zero-Click Diagnostic)",
    category: "ai-aeo",
    filterTarget: "Query",
    matchMode: "Matches regex",
    regex: "^([^\" \"]+\\s){9,}[^\" \"]+$",
    whatItFinds:
      "Ultra-long queries (10+ words) often generated by AI search grounding (ChatGPT/Perplexity fan-out queries) or voice search.",
    actionToTake:
      "High impressions + 0 clicks here means Google is using your page as a grounding source in AI Overviews. Turn these into explicit FAQ sections on the ranking URL.",
    exampleMatch: "can i sue a trucking company if the driver was an independent contractor",
  },
  {
    id: "ai-comparison-vs",
    title: "Comparison & 'Vs / Alternative' Evaluation Queries",
    category: "ai-aeo",
    filterTarget: "Query",
    matchMode: "Matches regex",
    regex: "\\b(vs|versus|compared to|alternative|alternatives|difference between|better than|or)\\b",
    whatItFinds:
      "Queries where searchers and LLMs compare two options, products, legal remedies, or service providers.",
    actionToTake:
      "Add a clean HTML <table> comparing the two entities side-by-side — Google AI Overviews and Perplexity extract comparison tables verbatim.",
    exampleMatch: "chapter 7 vs chapter 13 bankruptcy eligibility",
  },
  {
    id: "ai-step-by-step",
    title: "Process, Checklist & Step-by-Step Queries",
    category: "ai-aeo",
    filterTarget: "Query",
    matchMode: "Matches regex",
    regex: "\\b(how to|steps to|checklist|process|guide to|what happens when|what to do after)\\b",
    whatItFinds:
      "Procedural queries where AI Overviews synthesize numbered lists.",
    actionToTake:
      "Structure the answer using an ordered list (<ol><li>) with bolded lead-in steps so Google extracts your list as the featured snippet / AI citation.",
    exampleMatch: "what to do after a hit and run accident in wichita",
  },
  {
    id: "ai-cost-pricing-worth",
    title: "Cost, Pricing, Fee & ROI Justification Queries",
    category: "ai-aeo",
    filterTarget: "Query",
    matchMode: "Matches regex",
    regex: "\\b(cost|price|pricing|fees|how much|worth it|average settlement|hourly rate|retainer)\\b",
    whatItFinds:
      "Bottom-of-funnel pricing and settlement queries that drive the highest conversion rates.",
    actionToTake:
      "State real numbers, ranges, or fee structures in the first two sentences of the section rather than hiding behind 'it depends'.",
    exampleMatch: "how much does a personal injury lawyer take in california",
  },

  // ── 2. Law Firm SEO (Case-Intent & Practice Area Modifiers) ────────────────
  {
    id: "law-hire-attorney-intent",
    title: "Direct Attorney Hire Intent (Lawyer / Law Firm / Attorney)",
    category: "law-firm",
    filterTarget: "Query",
    matchMode: "Matches regex",
    regex: "\\b(lawyer|lawyers|attorney|attorneys|law firm|law office|legal help|counsel)\\b",
    whatItFinds:
      "Every query with explicit legal representation intent, separating real case prospects from student/informational legal lookups.",
    actionToTake:
      "Filter pages by Pos 4–15 on these queries. Improving internal links, attorney bio E-E-A-T, and local title tags here directly produces signed cases.",
    exampleMatch: "truck accident lawyer houston tx",
  },
  {
    id: "law-personal-injury-case",
    title: "Personal Injury High-Value Case Modifiers",
    category: "law-firm",
    filterTarget: "Query",
    matchMode: "Matches regex",
    regex: "\\b(car accident|truck accident|18 wheeler|motorcycle accident|wrongful death|slip and fall|brain injury|dog bite|uber accident|lyft accident)\\b",
    whatItFinds:
      "Core personal injury tort queries across all practice-area and blog pages.",
    actionToTake:
      "Check if blog posts are cannibalizing your main practice area page for any of these terms (click the Query -> Pages tab).",
    exampleMatch: "18 wheeler accident attorney near me",
  },
  {
    id: "law-settlement-payout",
    title: "Settlement Value, Payout & Compensation Queries",
    category: "law-firm",
    filterTarget: "Query",
    matchMode: "Matches regex",
    regex: "\\b(settlement|payout|compensation|verdict|worth|average payout|calculator|damages|pain and suffering)\\b",
    whatItFinds:
      "Injured claimants researching what their case is worth before calling a firm.",
    actionToTake:
      "Embed an interactive calculator or settlement breakdown table and a 24/7 intake CTA above the fold.",
    exampleMatch: "average settlement for rear end collision with herniated disc",
  },
  {
    id: "law-family-criminal",
    title: "Family Law & Criminal Defense Urgent Modifiers",
    category: "law-firm",
    filterTarget: "Query",
    matchMode: "Matches regex",
    regex: "\\b(divorce|child custody|alimony|prenup|dui|dwi|criminal defense|felony|misdemeanor|expungement|bail|domestic violence)\\b",
    whatItFinds:
      "High-urgency family and criminal defense queries.",
    actionToTake:
      "Ensure the ranking pages display click-to-call buttons, county court specifics, and immediate response guarantees.",
    exampleMatch: "emergency child custody lawyer sedgwick county",
  },
  {
    id: "law-informational-exclude",
    title: "Exclude Informational / Law-School Noise (Negative Filter)",
    category: "law-firm",
    filterTarget: "Query",
    matchMode: "Doesn't match regex",
    regex: "\\b(salary|jobs|internship|law school|bar exam|definition|meaning|pdf|template|reddit|quora)\\b",
    whatItFinds:
      "Strips out job seekers, law students, and template hunters so you see true client search demand.",
    actionToTake:
      "Combine with the Query filter when reporting monthly organic growth to partners.",
    exampleMatch: "(Excludes: 'paralegal salary texas', 'bar exam dates')",
  },

  // ── 3. Ecommerce & WooCommerce / Shopify SEO ───────────────────────────────
  {
    id: "ecom-buy-transactional",
    title: "Transactional Buy / Shop / Order Queries",
    category: "ecommerce",
    filterTarget: "Query",
    matchMode: "Matches regex",
    regex: "\\b(buy|order|shop|for sale|online|in stock|discount|coupon|promo|deal|cheap|free shipping|bulk|wholesale)\\b",
    whatItFinds:
      "High-intent commercial queries from shoppers ready to check out.",
    actionToTake:
      "Verify that product or category pages (not blog posts) rank for these queries and that Merchant Listing schema (price, availability) is valid.",
    exampleMatch: "buy benchmade bugout knife online in stock",
  },
  {
    id: "ecom-product-sku-model",
    title: "SKU, Model Number & Alphanumeric Product Searches",
    category: "ecommerce",
    filterTarget: "Query",
    matchMode: "Matches regex",
    regex: "\\b[a-zA-Z]{1,5}[- ]?[0-9]{2,6}[a-zA-Z0-9]*\\b",
    whatItFinds:
      "Shoppers searching exact manufacturer part numbers, SKUs, or model codes — the highest-converting traffic in ecommerce.",
    actionToTake:
      "Include exact manufacturer model numbers in H1s, title tags, and Product schema `mpn` / `sku` fields.",
    exampleMatch: "bm-535bk-2 in stock",
  },
  {
    id: "ecom-best-reviews-category",
    title: "Commercial Investigation ('Best / Top / Review') Queries",
    category: "ecommerce",
    filterTarget: "Query",
    matchMode: "Matches regex",
    regex: "\\b(best|top|review|reviews|rated|recommended|authentic|genuine|legit)\\b",
    whatItFinds:
      "Mid-to-bottom funnel shoppers comparing brands or verifying store legitimacy.",
    actionToTake:
      "Build buyer-guide blocks at the bottom of collection pages and display verified customer review counts.",
    exampleMatch: "best american made pocket knives for edc",
  },
  {
    id: "ecom-woo-shopify-product-urls",
    title: "Isolate Product & Collection Pages Only",
    category: "ecommerce",
    filterTarget: "Page",
    matchMode: "Matches regex",
    regex: "/(product|products|shop|collections|category|product-category|brand|brands)/",
    whatItFinds:
      "Filters GSC performance down to revenue-generating catalogue URLs on WooCommerce and Shopify.",
    actionToTake:
      "Compare 90-day clicks before and after catalogue indexing fixes to measure pure store revenue lift.",
    exampleMatch: "https://store.com/product-category/hunting-knives/",
  },

  // ── 4. Technical SEO & Indexing URL Filters (Page Filter) ──────────────────
  {
    id: "tech-parameter-urls",
    title: "URLs With Query Parameters (Crawl Waste & Duplicate Check)",
    category: "technical-urls",
    filterTarget: "Page",
    matchMode: "Matches regex",
    regex: "\\?.*=",
    whatItFinds:
      "Parameterized URLs (?orderby=, ?filter_, ?page=, ?s=, ?utm_, ?srsltid=) leaking into Google's index and wasting crawl budget.",
    actionToTake:
      "Consolidate with canonical tags and block non-essential sort/filter parameters in robots.txt.",
    exampleMatch: "https://store.com/shop/?orderby=price&add-to-cart=412",
  },
  {
    id: "tech-pagination-urls",
    title: "Paginated Archive & Category URLs (/page/2/, ?page=)",
    category: "technical-urls",
    filterTarget: "Page",
    matchMode: "Matches regex",
    regex: "(/page/[0-9]+/?|[?&]page=[0-9]+)",
    whatItFinds:
      "Paginated category or blog pages receiving impressions instead of the primary root category page.",
    actionToTake:
      "Ensure page 1 links directly to top priority products/subcategories so deep pagination isn't the only crawl path.",
    exampleMatch: "https://store.com/product-category/outdoor/page/14/",
  },
  {
    id: "tech-deep-folder-urls",
    title: "Deep Architecture URLs (4+ Folder Levels Deep)",
    category: "technical-urls",
    filterTarget: "Page",
    matchMode: "Matches regex",
    regex: "^https?://[^/]+/[^/]+/[^/]+/[^/]+/[^/]+/",
    whatItFinds:
      "Pages buried 4 or more directory levels deep, which often suffer from weak internal PageRank and 'Crawled – currently not indexed'.",
    actionToTake:
      "Flatten URL structure or add direct hub/footer links to high-value deep pages.",
    exampleMatch: "https://site.com/services/legal/texas/houston/truck-accidents/",
  },
  {
    id: "tech-non-https-or-www",
    title: "Protocol or Subdomain Split (http:// or non-canonical host)",
    category: "technical-urls",
    filterTarget: "Page",
    matchMode: "Matches regex",
    regex: "^http://",
    whatItFinds:
      "Any insecure HTTP URLs still earning impressions in a Domain Property due to missing 301 redirects.",
    actionToTake:
      "Enforce a single hop 301 redirect from HTTP and non-canonical hostnames to your canonical HTTPS URL.",
    exampleMatch: "http://www.example.com/about",
  },
  {
    id: "tech-staging-junk-urls",
    title: "Staging, Demo, Tag, Author or Feed Bloat URLs",
    category: "technical-urls",
    filterTarget: "Page",
    matchMode: "Matches regex",
    regex: "/(tag|tags|author|feed|wp-content|wp-json|cart|checkout|my-account|sample-page|test|demo)/",
    whatItFinds:
      "Thin taxonomy archives, WordPress system endpoints, or utility pages accidentally indexed by Google.",
    actionToTake:
      "Set noindex on thin tag/author archives and remove them from your XML sitemaps.",
    exampleMatch: "https://site.com/tag/uncategorized/feed/",
  },

  // ── 5. Local SEO & Map Pack Queries ────────────────────────────────────────
  {
    id: "local-near-me-proximity",
    title: "'Near Me' & Local Proximity Queries",
    category: "local-seo",
    filterTarget: "Query",
    matchMode: "Matches regex",
    regex: "\\b(near me|nearby|close to me|in my area|around me|local|closest)\\b",
    whatItFinds:
      "High-intent local searches where Google shows the 3-Pack Map results above organic links.",
    actionToTake:
      "Align your landing page H1, GBP primary category, and LocalBusiness schema `areaServed` with these exact services.",
    exampleMatch: "ac installation near me",
  },
  {
    id: "local-emergency-24-7",
    title: "Urgent / Same-Day / 24-Hour Local Service Queries",
    category: "local-seo",
    filterTarget: "Query",
    matchMode: "Matches regex",
    regex: "\\b(emergency|24/7|24 hour|same day|urgent|open now|weekend|tonight|after hours)\\b",
    whatItFinds:
      "Immediate-need callers (HVAC breakdown, emergency roofing, bail/DUI defense, injury intake).",
    actionToTake:
      "Create dedicated emergency service sections and ensure Google Business Profile hours reflect 24/7 availability where applicable.",
    exampleMatch: "24 hour emergency ac repair california",
  },
  {
    id: "local-location-pages",
    title: "Filter All City & State Location Pages",
    category: "local-seo",
    filterTarget: "Page",
    matchMode: "Matches regex",
    regex: "/(locations|location|areas-we-serve|service-areas|cities)/",
    whatItFinds:
      "Isolates all geographic landing pages so you can audit which cities are ranking and which have zero impressions.",
    actionToTake:
      "For cities with 0 impressions, verify they are in your XML sitemap, linked from a crawlable HTML footer/hub, and contain local proof.",
    exampleMatch: "https://www.searchprex.com/locations/kansas/wichita",
  },

  // ── 6. Questions & Buyer Intent ────────────────────────────────────────────
  {
    id: "intent-5w1h-questions",
    title: "All Question Queries (Who, What, Where, When, Why, How)",
    category: "questions-intent",
    filterTarget: "Query",
    matchMode: "Matches regex",
    regex: "^(who|what|where|when|why|how|can|does|is|should|will|do)\\b",
    whatItFinds:
      "Every question-phrased query your site already earns impressions for.",
    actionToTake:
      "Pick questions with high impressions and low CTR -> add them as exact H2/H3 subheadings on the ranking page.",
    exampleMatch: "how long does google take to index a new page",
  },
  {
    id: "intent-troubleshooting-fix",
    title: "Problem-Solving & Troubleshooting Queries (Fix / Error / Not Working)",
    category: "questions-intent",
    filterTarget: "Query",
    matchMode: "Matches regex",
    regex: "\\b(fix|error|issue|problem|not working|not indexing|dropped|lost|penalized|suspended|recover|recovery)\\b",
    whatItFinds:
      "Pain-driven searches from users actively trying to solve a broken system or ranking drop.",
    actionToTake:
      "High-converting lead magnet placement: offer a diagnostic checklist or free audit right after the troubleshooting steps.",
    exampleMatch: "discovered currently not indexed fix woocommerce",
  },
  {
    id: "intent-templates-checklists",
    title: "Link-Magnet Queries (Checklist, Template, Calculator, Tool)",
    category: "questions-intent",
    filterTarget: "Query",
    matchMode: "Matches regex",
    regex: "\\b(checklist|template|calculator|generator|tool|audit|scorecard|examples|playbook|cheat sheet)\\b",
    whatItFinds:
      "Searches for interactive utilities and downloadable frameworks — the #1 natural backlink earners in SEO.",
    actionToTake:
      "Turn high-impression static blog posts matching these terms into interactive web tools or checklists.",
    exampleMatch: "technical seo audit checklist",
  },
];
