// SMK Store — verified internal link pool (live sitemap se, Jul 2026)
// Product sitemap intentionally OFF hai — sirf category/brand URLs use karo.
export const SMK_VERIFIED_LINKS = [
  // Knives
  'https://www.smkstore.com/knives/',
  'https://www.smkstore.com/knives/premium-knives/',
  'https://www.smkstore.com/knives/locking-knives/',
  'https://www.smkstore.com/knives/traditional-pocket-knives/',
  'https://www.smkstore.com/knives/swiss-army-style/',
  'https://www.smkstore.com/knives/survival-knives/',
  'https://www.smkstore.com/knives/bowies/',
  'https://www.smkstore.com/knives/automatic-knives/',
  'https://www.smkstore.com/knives/assisted-opening/',
  'https://www.smkstore.com/knives/butterfly-knives/',
  'https://www.smkstore.com/knives/machetes/',
  'https://www.smkstore.com/knives/daggers/',
  'https://www.smkstore.com/knives/karambits/',
  'https://www.smkstore.com/knives/neck-knives/',
  'https://www.smkstore.com/knives/throwing-knives/',
  'https://www.smkstore.com/knives/rescue/',
  'https://www.smkstore.com/knives/bayonets-combat-knives/',
  'https://www.smkstore.com/knives/hunting-knife-sets/',
  // Sharpeners
  'https://www.smkstore.com/sharpeners/',
  'https://www.smkstore.com/sharpeners/manual/',
  'https://www.smkstore.com/sharpeners/stones/',
  'https://www.smkstore.com/sharpeners/rods-steels/',
  'https://www.smkstore.com/sharpeners/sharpening-sets/',
  'https://www.smkstore.com/sharpeners/electric-sharpeners/',
  'https://www.smkstore.com/sharpeners/paste-oil-compound/',
  // Lights & Batteries
  'https://www.smkstore.com/lights/',
  'https://www.smkstore.com/lights/flashlights/',
  'https://www.smkstore.com/lights/headlamps/',
  'https://www.smkstore.com/lights/weapon-mountable-lights/',
  'https://www.smkstore.com/lights/pen-lights/',
  'https://www.smkstore.com/lights/mini-lights/',
  'https://www.smkstore.com/lights/lanterns/',
  'https://www.smkstore.com/lights/batteries-and-charging-accessories/',
  'https://www.smkstore.com/everything-else/batteries/',
  // Camping & Survival
  'https://www.smkstore.com/camping-and-survival/',
  'https://www.smkstore.com/camping-and-survival/firestarting/',
  'https://www.smkstore.com/camping-and-survival/survival/',
  'https://www.smkstore.com/camping-and-survival/first-aid/',
  'https://www.smkstore.com/camping-and-survival/navigation/',
  'https://www.smkstore.com/camping-and-survival/camp-cooking/',
  // Lighters (Zippo relevant!)
  'https://www.smkstore.com/lighters-and-smoking-accessories/',
  'https://www.smkstore.com/lighters-and-smoking-accessories/lighters/',
  'https://www.smkstore.com/lighters-and-smoking-accessories/lighter-accessories/',
  // Multi-tools
  'https://www.smkstore.com/multi-tools/',
  'https://www.smkstore.com/multi-tools/full-size-tools/',
  'https://www.smkstore.com/multi-tools/mini-tools/',
  'https://www.smkstore.com/multi-tools/wallet-and-keychain-tools/',
  // Optics
  'https://www.smkstore.com/optics/',
  'https://www.smkstore.com/optics/magnifying-glasses/',
  'https://www.smkstore.com/optics/binoculars/',
  'https://www.smkstore.com/optics/monoculars/',
  'https://www.smkstore.com/optics/night-vision/',
  // Knifemaking
  'https://www.smkstore.com/knifemaking/',
  'https://www.smkstore.com/knifemaking/handles/',
  'https://www.smkstore.com/knifemaking/blades/',
  'https://www.smkstore.com/knifemaking/kits/',
  'https://www.smkstore.com/knifemaking/hardware/',
  // Protection & Defense
  'https://www.smkstore.com/protection-and-defense/',
  'https://www.smkstore.com/protection-and-defense/tactical-pens/',
  // Other key
  'https://www.smkstore.com/sheaths-and-storage/',
  'https://www.smkstore.com/kitchen/',
  'https://www.smkstore.com/kitchen/chefs-knives/',
  'https://www.smkstore.com/paracord-and-accessories/',
  'https://www.smkstore.com/cleaning-and-maintenance/',
  'https://www.smkstore.com/gear-bags-and-accessories/',
  'https://www.smkstore.com/fishing/',
  'https://www.smkstore.com/fishing/fillet-knives/',
  'https://www.smkstore.com/hunting-and-shooting/',
  'https://www.smkstore.com/razors-and-grooming/',
]